import Head from 'next/head'
import {Inter} from 'next/font/google'
import App from "@/components/App";
import {ThemeProvider} from "@mui/material";
import theme from "@/Theme/Theme";
import {Provider} from "react-redux";
import {setupStore} from "@/store/store";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    const store = setupStore();
    return (
        <>
            <Head>
                <title>Translator</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Provider store={store}>
                <ThemeProvider theme={theme}>
                    <App/>
                </ThemeProvider>
            </Provider>


        </>
    )
}
